language: generic
sudo: required
services:
  - docker


before_install:
 - docker build -t mborjas/docker-reactv2 -f Dockerfile.dev .

script:
 - docker run -e CI=true mborjas/docker-reactv2 npm run test